# Generated by Django 5.1.4 on 2025-01-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
