# Generated by Django 5.1.4 on 2025-01-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_order_address_order_mobile_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='mobile',
            new_name='mobileno',
        ),
    ]
